### ISSUE TITLE
Twilight Portal still allows teleport

### ISSUE THREAD

**Issue by devryb** [KaiKikuchi/DimRestrictor#1]
I made a restriction for 2-8am on DIM-7 which appeared to work however I was still able to teleport to the dimension via a twilight forest portal.  Once I got there it gave me a message that its currently restricted but as soon as I moved around I got internal server error:

This is what is listed in the server log:
[09:45:50] [Server thread/INFO]: Player touched the portal block.  Sending the player to dimension 7
[09:45:59] [Server thread/WARN]: Failed to handle packet for 127.0.0.1/127.0.0.1:55401
net.minecraft.util.ReportedException: Colliding entity with block
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:625) ~[sa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:536) ~[nh.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) ~[jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(C03PacketPlayer.java:144) ~[je.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
Caused by: java.lang.NullPointerException
	at com.emoniph.witchery.blocks.BlockDisease.func_149670_a(BlockDisease.java:70) ~[BlockDisease.class:?]
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:1063) ~[sa.class:?]
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:618) ~[sa.class:?]
	... 10 more
[09:45:59] [Server thread/INFO]: devryb lost connection: Internal server error
[09:45:59] [Server thread/INFO]: devryb left the game.

**Comment by devryb** [comment]
Ignore the error my testing with Witchery disease seems to be the cause of it

**Comment by devryb** [comment]
Ok tested with my Witchery issue fixed and it doesn't give an error at all but still allows teleport to the world with the twilight portal.  Setting a home in the twilight and then trying to teleport there works though so if there's no way to fix this we can just disable twilight portals and set a warp to it instead.

**Comment by KaiKikuchi** [comment]
I'll add an additional task that checks if the player is on the target world after a couple of seconds. If it's this case, the player will be teleported to the main world spawn.
