### ISSUE TITLE
Latest version issue

### ISSUE THREAD

**Issue by devryb** [KaiKikuchi/DimRestrictor#2]
Appears to no longer work in the latest version.
Also the console has this in it

[13:59:13] [Server thread/WARN]: [DimRestrictor] Task #277 for DimRestrictor v1.1 generated an exception
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922) ~[?:1.7.0_75]
	at java.util.HashMap$KeyIterator.next(HashMap.java:956) ~[?:1.7.0_75]
	at net.kaikk.mc.DimRestrictor.CheckTask.run(CheckTask.java:15) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:git-Cauldron-MCPC-Plus-1.7.10-1.1240.06.213]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1240.06.213]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:862) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]

**Comment by KaiKikuchi** [comment]
Fixed
